### ISSUE TITLE
Support ERC20 tfchain transactions

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscale_lib#273]
#### Installation information

- jumpscale version: 960
- operating system: N/A

#### Detailed description

It should be possible to send TFT to an ERC20 address, as well as be able to register an ERC20 withdrawal address, using the JS tfchain lib. 

#### Tasks

- [x] support encoding/decoding of ERC20 Transactions;
- [x] ability to register an ERC20 address;
- [x] ability to send coins to an ERC20 address (overloading the existing `send_money` method);
